import './globals.css'
import { Inter } from 'next/font/google'
import { useLocale } from "next-intl";
import {NextIntlClientProvider} from 'next-intl';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// export function generateStaticParams() {
//   const langCodes = [
//     "aa", "ab", "af", "ak", "sq", "am", "ar", "an", "hy", "as", "av", "ae", "ay", "az", "ba", "bm", "eu", "be", "bn", "bh", "bi", "bs", "br", "bg", "my", "ca", "cs", "ch", "ce", "ny", "zh", "cv", "kw", "co", "cr", "cy", "cs", "da", "de", "dv", "nl", "dz", "el", "en", "eo", "et", "eu", "ee", "fo", "fa", "fj", "fi", "fr", "ff", "gl", "ka", "de", "el", "gn", "gu", "ht", "ha", "he", "hz", "hi", "ho", "hr", "hu", "hy", "ig", "is", "io", "ii", "iu", "ie", "ia", "id", "ik", "is", "it", "jv", "ja", "kl", "kn", "ks", "kk", "km", "ki", "rw", "ky", "kv", "kg", "ko", "ku", "kj", "la", "lb", "lg", "li", "ln", "lo", "lt", "lu", "lv", "gv", "mk", "mg", "ms", "ml", "mt", "mi", "mr", "mh", "mn", "na", "nv", "nb", "nd", "ne", "ng", "nn", "no", "ii", "nr", "oc", "oj", "cu", "om", "or", "os", "pa", "pi", "fa", "pl", "ps", "pt", "qu", "rm", "rn", "ro", "ru", "sa", "sc", "sd", "se", "sm", "sg", "sr", "gd", "sn", "si", "sk", "sl", "so", "st", "es", "su", "sw", "ss", "sv", "ta", "te", "tg", "th", "ti", "bo", "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo", "wa", "cy", "wo", "fy", "xh", "yi", "yo", "za", "zu"
//   ]
//   //return [{locale: 'en'}, {locale: 'de'}];
//   return langCodes.map(item=>({locale:item}));
// }
export default async function RootLayout({ children,params }) {
  // const locale = useLocale();
  // if (params.locale !== locale) {
  //   //notFound();
  // }
  // let messages;
  // try {
  //   messages = (await import(`../messages/${locale}.json`)).default;
  // } catch (error) {
  //   //notFound();
  // }
  return (
    <html>
      <body className={inter.className} dir="ltr" cz-shortcut-listen="true">
        {/* <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider> */}
        {children}
      </body>
    </html>
  )
}
